### ISSUE TITLE
 Add navigation bar into index.html

### ISSUE THREAD

**Issue by joelabreurojas** [j4breu/web-typography#1]
Implement a navigation bar at the top of the index.html file for a webpage about web typography. The navbar should provide links for the following sections:

- [x] Web Fonts
- [x] History of Typography
- [x] Alignment
- [x] Indents
- [x] Spacing
- [x] Line Length

While the links won't navigate to separate pages, use # symbol as placeholder.

**Comment by j4breu** [comment]
Test
